"""Add OTP and verification fields to user

Revision ID: 286c65368d64
Revises: 48517b50db59
Create Date: 2026-03-17 09:49:23.972726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286c65368d64'
down_revision: Union[str, Sequence[str], None] = '48517b50db59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('otp_expire_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expire_at')
    op.drop_column('users', 'otp')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
