"""Add slug to policy table

Revision ID: 6711c81058f0
Revises: 4a33283f8c12
Create Date: 2026-03-30 16:15:33.416552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6711c81058f0'
down_revision: Union[str, Sequence[str], None] = '4a33283f8c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policys', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_policys_slug'), 'policys', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policys_slug'), table_name='policys')
    op.drop_column('policys', 'slug')
    # ### end Alembic commands ###
