"""Add social login fields

Revision ID: 7ff57fb823cb
Revises: 6711c81058f0
Create Date: 2026-04-20 09:55:53.712560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff57fb823cb'
down_revision: Union[str, Sequence[str], None] = '6711c81058f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('social_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_social_id'), 'users', ['social_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_social_id'), table_name='users')
    op.drop_column('users', 'social_id')
    op.drop_column('users', 'social_provider')
    # ### end Alembic commands ###
