"""Add new columns to BookScan

Revision ID: 95c723b92d18
Revises: 286c65368d64
Create Date: 2026-03-17 13:29:03.484021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c723b92d18'
down_revision: Union[str, Sequence[str], None] = '286c65368d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookscans', sa.Column('cover_image_url', sa.String(), nullable=True))
    op.add_column('bookscans', sa.Column('rating_score', sa.Integer(), nullable=True))
    op.add_column('bookscans', sa.Column('recommended_age', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookscans', 'recommended_age')
    op.drop_column('bookscans', 'rating_score')
    op.drop_column('bookscans', 'cover_image_url')
    # ### end Alembic commands ###
